#### Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [152]:
import pandas as pd
import numpy as np

# Verify installation
print(pd.__version__)

2.3.2

In [153]:
import pandas as pd

# Create a simple list
data = [1, 2, 3, 4, 5]

# Convert list to Series
series = pd.Series(data)

# Display the Series
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [154]:
## Series
## Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.
print(type(series))

<class 'pandas.core.series.Series'>

In [155]:
# Create a dictionary
data = {'a': 1, 'b': 2, 'c': 3}

# Dictionary keys become the INDEX
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [156]:
data = [10, 20, 30]
my_index = ['a', 'b', 'c']

# Provide custom index explicitly
series_custom = pd.Series(data, index=my_index)
print(series_custom)

a    10
b    20
c    30
dtype: int64

In [157]:
# Integer Series
int_series   = pd.Series([1, 2, 3, 4])   
print(int_series)

0    1
1    2
2    3
3    4
dtype: int64

In [158]:
# Float Series
flt_series   = pd.Series([1.1, 2.2, 3.3])      
print(flt_series)

0    1.1
1    2.2
2    3.3
dtype: float64

In [159]:
# String Series
str_series   = pd.Series(['Asbin', 'Binod'])     
print(str_series)

0    Asbin
1    Binod
dtype: object

In [160]:
# Boolean Series
bool_series  = pd.Series([True, False, True])  
print(bool_series)

0     True
1    False
2     True
dtype: bool

In [161]:
mix_series   = pd.Series([1, 'two', 3.0]) 
print(mix_series)

0      1
1    two
2    3.0
dtype: object

In [162]:
s = pd.Series([10, 20, 30, 40], index=['a','b','c','d'])

print(s.dtype)      
print(s.shape)      
print(s.size)    
print(s.index)    
print(s.values)  
print(s.is_unique)

int64
(4,)
4
Index(['a', 'b', 'c', 'd'], dtype='object')
[10 20 30 40]
True

In [163]:
s1 = pd.Series([10, 20, 30])
s2 = pd.Series([1, 2, 3])

# Arithmetic — element-wise (vectorized)
print(s1 + s2)  
print(s1 - s2)  
print(s1 * s2) 
print(s1 / s2)

0    11
1    22
2    33
dtype: int64
0     9
1    18
2    27
dtype: int64
0    10
1    40
2    90
dtype: int64
0    10.0
1    10.0
2    10.0
dtype: float64

In [164]:
# Scalar operations
print(s1 + 100) 
print(s1 ** 2)    

# Boolean / comparison
print(s1 > 15)

0    110
1    120
2    130
dtype: int64
0    100
1    400
2    900
dtype: int64
0    False
1     True
2     True
dtype: bool

In [165]:
s = pd.Series([10, 20, 30, 40, 50], index=['a','b','c','d','e'])

# By label (loc) 
print(s['a'])         
print(s[['a', 'c']])   
print(s['a':'c'])

10
a    10
c    30
dtype: int64
a    10
b    20
c    30
dtype: int64

In [166]:
# By position (iloc)
print(s[0])      
print(s[0:3])        
print(s[-1])

10
a    10
b    20
c    30
dtype: int64
50

C:\Windows\Temp\ipykernel_34132\1437667576.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])
C:\Windows\Temp\ipykernel_34132\1437667576.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[-1])

In [167]:
# Boolean indexing
print(s[s > 25])

c    30
d    40
e    50
dtype: int64

In [168]:
import pandas as pd

# Dictionary of lists — most common method
data = {
    'Name': ['Krishna', 'Jivan', 'Jamuna'],
    'Age':  [25, 30, 45],
    'City': ['Biratnagar', 'Kathmandu', 'Pokhara']
}

df = pd.DataFrame(data)
print(df)

      Name  Age        City
0  Krishna   25  Biratnagar
1    Jivan   30   Kathmandu
2   Jamuna   45     Pokhara

In [169]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [170]:
# Each dictionary = one ROW of data
data = [
    {'Name': 'Krishna', 'Age': 32, 'City': 'Biratnagar'},
    {'Name': 'Jivan',  'Age': 34, 'City': 'Kathmandu'},
    {'Name': 'Jamuna',  'Age': 32, 'City': 'Pokhara'}
]

df = pd.DataFrame(data)
print(df)

      Name  Age        City
0  Krishna   32  Biratnagar
1    Jivan   34   Kathmandu
2   Jamuna   32     Pokhara

In [171]:
import numpy as np
np.array(df)

array([['Krishna', 32, 'Biratnagar'],
       ['Jivan', 34, 'Kathmandu'],
       ['Jamuna', 32, 'Pokhara']], dtype=object)

In [172]:
# Basic CSV reading
df = pd.read_csv('sales_data.csv')
df.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [173]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [174]:
# Install openpyxl first: pip install openpyxl

# Basic Excel reading
df = pd.read_excel('data.xlsx')

In [175]:
df.head()

    Name  Age
0  Nabin   32
1   Jack   34
2   John   31

In [176]:
df = pd.read_csv('sales_data.csv')

df.head()         
df.head(10)      
df.tail()         
df.tail(3)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [177]:
df.shape

(240, 9)

In [178]:
df.columns

Index(['Transaction ID', 'Date', 'Product Category', 'Product Name',
       'Units Sold', 'Unit Price', 'Total Revenue', 'Region',
       'Payment Method'],
      dtype='object')

In [179]:
df.index

RangeIndex(start=0, stop=240, step=1)

In [180]:
df.dtypes

Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object

In [181]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    240 non-null    int64
 1   Date              240 non-null    object
 2   Product Category  240 non-null    object
 3   Product Name      240 non-null    object
 4   Units Sold        240 non-null    int64
 5   Unit Price        240 non-null    float64
 6   Total Revenue     240 non-null    float64
 7   Region            240 non-null    object
 8   Payment Method    240 non-null    object
dtypes: float64(2), int64(2), object(5)
memory usage: 17.0+ KB

In [182]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [183]:
### Accessing Data From Dataframe
data

[{'Name': 'Krishna', 'Age': 32, 'City': 'Biratnagar'},
 {'Name': 'Jivan', 'Age': 34, 'City': 'Kathmandu'},
 {'Name': 'Jamuna', 'Age': 32, 'City': 'Pokhara'}]

In [184]:
df = pd.DataFrame(data)
print(df)

      Name  Age        City
0  Krishna   32  Biratnagar
1    Jivan   34   Kathmandu
2   Jamuna   32     Pokhara

In [185]:
df

      Name  Age        City
0  Krishna   32  Biratnagar
1    Jivan   34   Kathmandu
2   Jamuna   32     Pokhara

In [186]:
df['Name']

0    Krishna
1      Jivan
2     Jamuna
Name: Name, dtype: object

In [187]:
df.Name

0    Krishna
1      Jivan
2     Jamuna
Name: Name, dtype: object

In [188]:
type(df['Name'])

pandas.core.series.Series

In [189]:
df.loc[0]

Name       Krishna
Age             32
City    Biratnagar
Name: 0, dtype: object

In [190]:
df.loc[0, 'Name']

'Krishna'

In [191]:
df.loc[0:2]

      Name  Age        City
0  Krishna   32  Biratnagar
1    Jivan   34   Kathmandu
2   Jamuna   32     Pokhara

In [192]:
df.loc[:, 'Name']

0    Krishna
1      Jivan
2     Jamuna
Name: Name, dtype: object

In [193]:
df.iloc[0]

Name       Krishna
Age             32
City    Biratnagar
Name: 0, dtype: object

In [194]:
df.iloc[0, 1]

32

In [195]:
df.iloc[0:3]

      Name  Age        City
0  Krishna   32  Biratnagar
1    Jivan   34   Kathmandu
2   Jamuna   32     Pokhara

In [196]:
df.iloc[:, 0]

0    Krishna
1      Jivan
2     Jamuna
Name: Name, dtype: object

In [197]:
df

      Name  Age        City
0  Krishna   32  Biratnagar
1    Jivan   34   Kathmandu
2   Jamuna   32     Pokhara

In [198]:
print(df.loc[1])

Name        Jivan
Age            34
City    Kathmandu
Name: 1, dtype: object

In [199]:
print(df.loc[0, 'Name'])

Krishna

In [200]:
print(df.iloc[2, 2])

Pokhara

In [201]:
print(df.loc[df['Age'] > 28])

      Name  Age        City
0  Krishna   32  Biratnagar
1    Jivan   34   Kathmandu
2   Jamuna   32     Pokhara

In [202]:
## Accessing a specified element
df.at[2,'Age']

32

In [203]:
df.at[2,'Name']

'Jamuna'

In [204]:
## Accessing a specified element using iat
df.iat[2,2]

'Pokhara'

In [205]:
df

      Name  Age        City
0  Krishna   32  Biratnagar
1    Jivan   34   Kathmandu
2   Jamuna   32     Pokhara

In [206]:
### Data MAnipulation with Dataframe
df

      Name  Age        City
0  Krishna   32  Biratnagar
1    Jivan   34   Kathmandu
2   Jamuna   32     Pokhara

In [207]:
## Adding a column
df['Salary']=[50000,60000,70000]
df

      Name  Age        City  Salary
0  Krishna   32  Biratnagar   50000
1    Jivan   34   Kathmandu   60000
2   Jamuna   32     Pokhara   70000

In [208]:
df['Salary_k'] = df['Salary'] / 1000      
df

      Name  Age        City  Salary  Salary_k
0  Krishna   32  Biratnagar   50000      50.0
1    Jivan   34   Kathmandu   60000      60.0
2   Jamuna   32     Pokhara   70000      70.0

In [209]:
df['Salary_k'] = df['Salary'] / 1000     
df

      Name  Age        City  Salary  Salary_k
0  Krishna   32  Biratnagar   50000      50.0
1    Jivan   34   Kathmandu   60000      60.0
2   Jamuna   32     Pokhara   70000      70.0

In [210]:
df['Country'] = 'Nepal'

In [211]:
## Remove a column
df.drop('Salary_k',axis=1,inplace=True)

In [212]:
df

      Name  Age        City  Salary Country
0  Krishna   32  Biratnagar   50000   Nepal
1    Jivan   34   Kathmandu   60000   Nepal
2   Jamuna   32     Pokhara   70000   Nepal

In [213]:
## Add age to the column
df['Age']=df['Age']+1
df

      Name  Age        City  Salary Country
0  Krishna   33  Biratnagar   50000   Nepal
1    Jivan   35   Kathmandu   60000   Nepal
2   Jamuna   33     Pokhara   70000   Nepal

In [214]:
df.drop('Salary', axis=1)                  
df.drop('Salary', axis=1, inplace=True)

In [215]:
df

      Name  Age        City Country
0  Krishna   33  Biratnagar   Nepal
1    Jivan   35   Kathmandu   Nepal
2   Jamuna   33     Pokhara   Nepal

In [216]:
# Drop multiple columns
df.drop(['City', 'Country'], axis=1, inplace=True)

In [217]:
df

      Name  Age
0  Krishna   33
1    Jivan   35
2   Jamuna   33

In [218]:
df.drop(0,inplace=True)

In [219]:
df

     Name  Age
1   Jivan   35
2  Jamuna   33

In [220]:
df.drop([1,2], inplace=True) # Drop rows 0 and 1 permanently

In [221]:
df

Empty DataFrame
Columns: [Name, Age]
Index: []

In [222]:

# Drop duplicate rows 
df.drop_duplicates(inplace=True)

Empty DataFrame
Columns: [Name, Age]
Index: []

In [223]:
data = {'Name':['Krishna','John','Jack'], 'Age':[25,30,45], 'City':['Kathmandu','New York','Florida']}
df = pd.DataFrame(data)
df

      Name  Age       City
0  Krishna   25  Kathmandu
1     John   30   New York
2     Jack   45    Florida

In [224]:
# Add 1 to all ages (vectorized) 
df['Age'] = df['Age'] + 1

In [225]:
df

      Name  Age       City
0  Krishna   26  Kathmandu
1     John   31   New York
2     Jack   46    Florida

In [226]:
# Apply string method to entire column 
df['Name'] = df['Name'].str.upper()


print(df)

      Name  Age       City
0  KRISHNA   26  Kathmandu
1     JOHN   31   New York
2     JACK   46    Florida

In [227]:


# Replace specific values 
df['City'] = df['City'].replace('Kathmandu', 'Pokhara')
df

      Name  Age      City
0  KRISHNA   26   Pokhara
1     JOHN   31  New York
2     JACK   46   Florida

In [228]:
# Change a specific cell
df.at[0, 'Age'] = 100       
df

      Name  Age      City
0  KRISHNA  100   Pokhara
1     JOHN   31  New York
2     JACK   46   Florida

In [229]:
df.loc[0, 'Name'] = 'Rohan'

In [230]:
df

    Name  Age      City
0  Rohan  100   Pokhara
1   JOHN   31  New York
2   JACK   46   Florida

In [231]:
df = pd.DataFrame({'Name':['Krishna','John','Jack','Sara'],
                   'Age':[25,30,45,22], 'Salary':[50000,60000,90000,35000]})

# Single condition 
df[df['Age'] > 28]

   Name  Age  Salary
1  John   30   60000
2  Jack   45   90000

In [232]:

df[(df['Age'] > 25) & (df['Salary'] > 50000)]

   Name  Age  Salary
1  John   30   60000
2  Jack   45   90000

In [233]:
# OR condition
df[(df['Age'] < 26) | (df['Age'] > 40)]

      Name  Age  Salary
0  Krishna   25   50000
2     Jack   45   90000
3     Sara   22   35000

In [234]:
# NOT condition 
df[~(df['Name'] == 'Jack')]

      Name  Age  Salary
0  Krishna   25   50000
1     John   30   60000
3     Sara   22   35000

In [235]:
# .isin() filter
df[df['Name'].isin(['Krish', 'Sara'])]

   Name  Age  Salary
3  Sara   22   35000

In [236]:
# .query() — more readable syntax 
df.query('Age > 28 and Salary > 50000')

   Name  Age  Salary
1  John   30   60000
2  Jack   45   90000

In [237]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [238]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("Statistical summary:\n", df.describe())

Data types:
 Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object
Statistical summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [239]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000